In [2]:
import pandas as pd
import joblib
from pydantic import BaseModel
from typing import Dict
import pickle

Leer csv coches disponibles:

In [4]:
df_coches = pd.read_csv(
    "../../artifacts/data/coches_disponibles.csv"
)

In [47]:
#renombrar columna tipo_combustible a tipo_combustible.1 para que no se confunda con la del usuario
df_coches = df_coches.rename(columns={'tipo_combustible': 'tipo_combustible.1'})

In [48]:
from pydantic import BaseModel
from typing import Dict

# Definir la clase de datos del formulario
class DatosFormulario(BaseModel):
    renta: str
    condiciones_conduccion: str
    vacaciones: str
    sector: str
    comunidad_autonoma: str
    familia: str
    tipo_combustible: str
    frecuencia_uso: str
    cambio: str
    plaza_parking: str
    experiencia_conduccion: str

# Suponiendo que tienes un JSON de usuario que ya has cargado:
datos_usuario_json = {
    "renta": "12000 - 20000", 
    "condiciones_conduccion": "off-road", 
    "vacaciones": "Montaña", 
    "sector": "Educación", 
    "comunidad_autonoma": "Canarias", 
    "familia": "No", 
    "tipo_combustible": "gasolina", 
    "frecuencia_uso": "diario", 
    "cambio": "Manual", 
    "plaza_parking": "sí", 
    "experiencia_conduccion": "intermedio"
}

# Crear un objeto del formulario con el JSON
usuario = DatosFormulario(**datos_usuario_json)

# Convertir los datos del usuario en un diccionario
usuario_dict = usuario.dict()

# Replicar los datos del usuario en cada fila del CSV de coches
for key, value in usuario_dict.items():
    df_coches[key] = value  # Esto añade una nueva columna por cada dato del usuario

C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\384289944.py:37: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
  usuario_dict = usuario.dict()

In [49]:
df_coches

,Maker,Version,Price,URL Producto,URL Imagen,Year,Kms,Potencia,Caja_velocidades,presupuesto,...,condiciones_conduccion,vacaciones,sector,comunidad_autonoma,familia,tipo_combustible,frecuencia_uso,cambio,plaza_parking,experiencia_conduccion
0,Abarth 595,1.4T JET,16590.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2022,35.973km,145CV,Manual,"15,000-20,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
1,Abarth 595,595C 1.4T JET TURISMO AUT.,16390.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2021,63.037km,165CV,Automatico,"15,000-20,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
2,Abarth 595,595C 1.4T JET TURISMO AUT.,18190.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2021,63.843km,165CV,Automatico,"15,000-20,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
3,Alfa Romeo Giulietta,1.6JTD Super 120,12690.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2019,139.248km,120CV,Manual,"10,000-15,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
4,Alfa Romeo Stelvio,2.2 Veloce Q4 210 Aut.,25490.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2021,137.749km,210CV,Automatico,"20,000-30,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1819,Volvo XC60,D5 R-Design AWD Aut.,33290.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2019,95.844km,235CV,Automatico,"30,000-40,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
1820,Volvo XC60,T6 Twin Recharge Inscription Expression,31990.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2021,72.014km,340CV,Automatico,"30,000-40,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
1821,Volvo XC60,T8 Twin Recharge Inscription,32390.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2020,90.767km,390CV,Automatico,"30,000-40,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
1822,Volvo XC90,B5 Momentum Pro 7pl. AWD Aut.,37090.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2020,120.339km,235CV,Automatico,"30,000-40,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio
1823,Volvo XC90,T8 Twin Momentum AWD Aut.,38090.0,https://www.clicars.com/coches-segunda-mano-oc...,https://storage.googleapis.com/clicars-storage...,2019,112.596km,390CV,Automatico,"30,000-40,000",...,off-road,Montaña,Educación,Canarias,No,gasolina,diario,Manual,sí,intermedio

Procesado:

In [50]:
df_coches = df_coches.drop(columns=['presupuesto'])

In [51]:
#Columnas para pasar a boolean:
columns_to_convert = ['plaza_parking']

# Convertir una columna con valores 'sí'/'no' a booleanos (True/False)
df_coches[columns_to_convert] = df_coches[columns_to_convert].replace({'sí': True, 'no': False})

# Asegurar de que la columna sea de tipo booleano
df_coches[columns_to_convert] = df_coches[columns_to_convert].astype(bool)

C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2935722055.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_coches[columns_to_convert] = df_coches[columns_to_convert].replace({'sí': True, 'no': False})

In [52]:
# Quitamos el "km" para que el campo sea numérico
df_coches['Kms'] = df_coches['Kms'].str.replace('km', '', regex=False)

# Convertir la columna a tipo numérico
df_coches['Kms'] = pd.to_numeric(df_coches['Kms'], errors='coerce')

# Quitamos el "CV" para que el campo sea numérico
df_coches['Potencia'] = df_coches['Potencia'].str.replace('CV', '', regex=False)

# Convertir la columna a tipo numérico
df_coches['Potencia'] = pd.to_numeric(df_coches['Potencia'], errors='coerce')

Encoding:

In [53]:
# Label Encoding

#Renta
renta_mapping = {
    '-12000': 0,
    '12000 - 20000': 1,
    '20000 - 35000': 2,
    '35000-60000': 3,
    '60000 - 100000': 4,
    '100000': 5
}


df_coches['renta_encoded'] = df_coches['renta'].map(renta_mapping)

#Familia
familia_mapping = {
    'No': 0,
    'Si, pequeña': 1,
    'Si, grande': 2,
}


df_coches['familia_encoded'] = df_coches['familia'].map(familia_mapping)

#freq.uso:
frecuencia_uso_mapping = {
    'ocasional': 0,
    'semanal': 1,
    'diario': 2,
}


df_coches['frecuencia_uso_encoded'] = df_coches['frecuencia_uso'].map(frecuencia_uso_mapping)

#Exp. conduccion
experiencia_conduccion_mapping = {
    'novato': 0,
    'intermedio': 1,
    'experto': 2,
}


df_coches['experiencia_conduccion_encoded'] = df_coches['experiencia_conduccion'].map(experiencia_conduccion_mapping)

In [54]:
# Aplicar Mapeo de frequency encoding:

# Lista de las columnas codificadas
columnas_a_codificar = [
    'vacaciones', 
    'sector', 
    'comunidad_autonoma', 
    'condiciones_conduccion', 
    'Caja_velocidades', 
    'tipo_combustible',
    'tipo_combustible.1',
    'Marca'
]

# Aplicar el mapeo de frecuencias a df_coches
for col in columnas_a_codificar:
    # Cargar el mapeo guardado para cada columna
    freq_encoding = pd.read_pickle(f'C:/Users/swatc/Desktop/UNI/Proyecto grupal/Automatch/artifacts/data/{col}_freq_map.pkl')
    
    # Aplicar el Frequency Encoding al nuevo DataFrame (df_coches)
    df_coches[f'{col}_freq'] = df_coches[col].map(freq_encoding)
    
    # Si hay valores desconocidos, asignar un valor por defecto (0 o NaN)
    df_coches[f'{col}_freq'].fillna(0, inplace=True)

C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2927753808.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coches[f'{col}_freq'].fillna(0, inplace=True)
C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2927753808.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coches[f'{col}_freq'].fillna(0, inplace=True)
C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2927753808.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coches[f'{col}_freq'].fillna(0, inplace=True)
C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2927753808.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coches[f'{col}_freq'].fillna(0, inplace=True)
C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2927753808.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coches[f'{col}_freq'].fillna(0, inplace=True)
C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2927753808.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coches[f'{col}_freq'].fillna(0, inplace=True)
C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2927753808.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coches[f'{col}_freq'].fillna(0, inplace=True)
C:\Users\swatc\AppData\Local\Temp\ipykernel_13348\2927753808.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coches[f'{col}_freq'].fillna(0, inplace=True)

In [55]:
df_coches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1824 entries, 0 to 1823
Data columns (total 36 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Maker                           1824 non-null   object
 1   Version                         1822 non-null   object
 2   Price                           1824 non-null   float64
 3   URL Producto                    1824 non-null   object
 4   URL Imagen                      1824 non-null   object
 5   Year                            1824 non-null   int64
 6   Kms                             1823 non-null   float64
 7   Potencia                        1824 non-null   int64
 8   Caja_velocidades                1824 non-null   object
 9   tipo_combustible.1              1824 non-null   object
 10  Puertas                         1824 non-null   int64
 11  Plazas                          1824 non-null   int64
 12  Marca                           1824 non-null   object
 13  renta                           1824 non-null   object
 14  condiciones_conduccion          1824 non-null   object
 15  vacaciones                      1824 non-null   object
 16  sector                          1824 non-null   object
 17  comunidad_autonoma              1824 non-null   object
 18  familia                         1824 non-null   object
 19  tipo_combustible                1824 non-null   object
 20  frecuencia_uso                  1824 non-null   object
 21  cambio                          1824 non-null   object
 22  plaza_parking                   1824 non-null   bool
 23  experiencia_conduccion          1824 non-null   object
 24  renta_encoded                   1824 non-null   int64
 25  familia_encoded                 1824 non-null   int64
 26  frecuencia_uso_encoded          1824 non-null   int64
 27  experiencia_conduccion_encoded  1824 non-null   int64
 28  vacaciones_freq                 1824 non-null   float64
 29  sector_freq                     1824 non-null   float64
 30  comunidad_autonoma_freq         1824 non-null   float64
 31  condiciones_conduccion_freq     1824 non-null   float64
 32  Caja_velocidades_freq           1824 non-null   float64
 33  tipo_combustible_freq           1824 non-null   float64
 34  tipo_combustible.1_freq         1824 non-null   float64
 35  Marca_freq                      1824 non-null   float64
dtypes: bool(1), float64(10), int64(8), object(17)
memory usage: 500.7+ KB

In [56]:
# Quitar cpolumnas innecesarias:
df_coches = df_coches.drop(columns=[
    'renta', 'URL Producto', 'URL Imagen', 'condiciones_conduccion','vacaciones', 'sector', 'comunidad_autonoma', 'familia',
    'tipo_combustible.1', 'cambio','frecuencia_uso','experiencia_conduccion', 'Maker', 'Version',
    'Caja_velocidades','tipo_combustible', 'Marca'])

In [57]:
df_coches.head()

,Price,Year,Kms,Potencia,Puertas,Plazas,plaza_parking,renta_encoded,familia_encoded,frecuencia_uso_encoded,experiencia_conduccion_encoded,vacaciones_freq,sector_freq,comunidad_autonoma_freq,condiciones_conduccion_freq,Caja_velocidades_freq,tipo_combustible_freq,tipo_combustible.1_freq,Marca_freq
0,16590.0,2022,35.973,145,4,4,True,1,0,2,1,0.0,0.050414,0.05011,0.092487,0.590234,0.298648,0.397041,0.000487
1,16390.0,2021,63.037,165,4,4,True,1,0,2,1,0.0,0.050414,0.05011,0.092487,0.409766,0.298648,0.397041,0.000487
2,18190.0,2021,63.843,165,4,4,True,1,0,2,1,0.0,0.050414,0.05011,0.092487,0.409766,0.298648,0.397041,0.000487
3,12690.0,2019,139.248,120,4,5,True,1,0,2,1,0.0,0.050414,0.05011,0.092487,0.590234,0.298648,0.301449,0.003897
4,25490.0,2021,137.749,210,4,5,True,1,0,2,1,0.0,0.050414,0.05011,0.092487,0.409766,0.298648,0.301449,0.003897

Leer picke:

In [58]:
# cargar picke
model = joblib.load(
    "C:/Users/swatc/Desktop/UNI/Proyecto grupal/Automatch/artifacts/data/modelo_users_cars1.pkl"
    )

In [59]:
df_coches.columns.tolist()

['Price',
 'Year',
 'Kms',
 'Potencia',
 'Puertas',
 'Plazas',
 'plaza_parking',
 'renta_encoded',
 'familia_encoded',
 'frecuencia_uso_encoded',
 'experiencia_conduccion_encoded',
 'vacaciones_freq',
 'sector_freq',
 'comunidad_autonoma_freq',
 'condiciones_conduccion_freq',
 'Caja_velocidades_freq',
 'tipo_combustible_freq',
 'tipo_combustible.1_freq',
 'Marca_freq']

In [60]:
columnas_para_prediccion = [
    'Price',
    'Year',
    'Kms',
    'Potencia',
    'renta_encoded',
    'familia_encoded',
    'frecuencia_uso_encoded',
    'experiencia_conduccion_encoded',
    'vacaciones_freq',
    'sector_freq',
    'comunidad_autonoma_freq',
    'condiciones_conduccion_freq',
    'tipo_combustible.1_freq',
    'Marca_freq'
]

Aplicar modelo:

In [61]:
df_input = df_coches[columnas_para_prediccion]

# Hacer las predicciones
y_pred = model.predict_proba(df_input)
y_pred_class = y_pred[:, 1]  # Probabilidad de la clase 1 (positiva)

In [62]:
#guardar predicciones
df_coches['prediccion'] = y_pred_class  # Agregar las predicciones a un nuevo dataframe
df_coches.to_csv("C:/Users/swatc/Desktop/UNI/Proyecto grupal/Automatch/artifacts/data/resultados2.csv", index=False)